jobs:
  include:
    - stage: test
      language: python
      python:
        - '3.7'
      services: 
        - mysql
      env:
        -DJANGO=2.2.5 DB=mysql
      install:
      - pip install -r requirements.txt
      before_script:
      - mysql -e 'create database zrstats;' -u root
      script:
      - python3 manage.py test
    - stage: release
      language: bash
      script:
      - nvm install lts/*
      - npm install @semantic-release/changelog -D
      - npm install @semantic-release/git -D
      - npx semantic-release
    - stage: build
      language: python
      python:
        - '3.7'
      branches:
        only:
        - master
      install:
      - pip install paramiko
      - pip install spur
      script:
      - python3 builder.py
