jobs:
  include:
    - stage: test
      language: python
      python:
        - '3.7'
      install:
      - pip install -r requirements.txt
      script:
      - python3 asistencia/tests.py
    - stage: release
      language: bash
      script:
      - nvm install lts/*
      - npm install @semantic-release/changelog -D
      - npm install @semantic-release/git -D
      - npx semantic-release
