# Generated by Django 2.2.5 on 2019-09-17 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre Campaña')),
                ('tipo', models.CharField(choices=[('CAMP', 'Campaña Oficial'), ('CURSO', 'Curso'), ('OTRO', 'Otros')], default=('CAMP', 'Campaña Oficial'), max_length=20, verbose_name='Tipo Campaña')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('EN CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada')], default=('BORRADOR', 'Borrador'), max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=20, verbose_name='Clase')),
                ('abreviatura', models.CharField(default='-', max_length=10, verbose_name='Abrev.')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('nombre', models.CharField(max_length=20, null=True, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Reserva', 'Reserva'), ('Licencia', 'Licencia'), ('No Miembro', 'No Miembro')], default=('Activo', 'Activo'), max_length=20, verbose_name='Estado')),
                ('peloton', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pelotón')),
                ('escuadra', models.CharField(blank=True, max_length=20, null=True, verbose_name='Escuadra')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Imagen de Avatar')),
                ('clase1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clase1', to='stats.Clase', verbose_name='Clase 1')),
                ('clase2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clase2', to='stats.Clase', verbose_name='Clase 2')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=20, verbose_name='Rango')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Unidad')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de Misión')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Creación')),
                ('tipo', models.CharField(choices=[('OFI', 'Misión Oficial'), ('PRACT', 'Práctica'), ('IMPRO', 'Improvisada'), ('GALA', 'Gala'), ('INSTR', 'Instrucción'), ('COOP', 'Cooperativa'), ('OTRO', 'Otros')], default=('OFI', 'Misión Oficial'), max_length=40, verbose_name='Tipo de misión')),
                ('estado', models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('PEND.APROB.', 'Pendiende de aprobación'), ('EN EDICION', 'En edición'), ('PREPARADA', 'Lista para jugar'), ('RECHAZADA', 'Rechazada'), ('FINALIZADA', 'Finalizada')], default=('BORRADOR', 'Borrador'), max_length=40, null=True, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (pública)')),
                ('notas_privadas', models.TextField(blank=True, null=True, verbose_name='Notas Privadas')),
                ('notas_editor', models.TextField(blank=True, null=True, verbose_name='Notas al Editor')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mision_logo/', verbose_name='Imagen')),
                ('briefing', models.FileField(blank=True, null=True, upload_to='briefings/', verbose_name='Briefing')),
                ('mapa', models.CharField(blank=True, max_length=40, null=True, verbose_name='Mapa')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('fecha_finalizada', models.DateField(blank=True, null=True, verbose_name='Fecha Finalizada')),
                ('reporte', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Miembro', verbose_name='Autor')),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Campana', verbose_name='Campaña')),
                ('editores', models.ManyToManyField(blank=True, related_name='misiones_editadas', to='stats.Miembro', verbose_name='Editores')),
                ('responsables', models.ManyToManyField(blank=True, related_name='misiones_a_cargo', to='stats.Miembro', verbose_name='Responsables')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='miembro',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Nacionalidad', verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='rango',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Rango', verbose_name='Rango'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Rol', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Unidad', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('asistencia', models.CharField(choices=[('Asiste', 'Asiste'), ('Falta', 'Falta'), ('Atraso', 'Atraso'), ('Justificado', 'Justificado'), ('Reserva', 'Reserva'), ('Licencia', 'Licencia')], max_length=20, verbose_name='Asistencia')),
                ('tiempo_de_sesion', models.DurationField(default=0, verbose_name='Tiempo de Sesión')),
                ('requiere_atencion', models.BooleanField(default=False, verbose_name='Requiere Atención')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Miembro', verbose_name='Miembro')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Mision', verbose_name='Mision')),
            ],
            options={
                'ordering': ('-pk',),
                'unique_together': {('miembro', 'fecha')},
            },
        ),
    ]
