# Generated by Django 2.2.9 on 2020-02-05 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombre Campaña')),
                ('tipo', models.CharField(choices=[('CAMP', 'Campaña Oficial'), ('CURSO', 'Curso'), ('OTRO', 'Otros')], default='CAMPANA', max_length=20, verbose_name='Tipo Campaña')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('notas_privadas', models.TextField(blank=True, null=True, verbose_name='Notas Privadas')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='campana_img/', verbose_name='Imagen')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=20, verbose_name='Clase')),
                ('abreviatura', models.CharField(default='-', max_length=10, verbose_name='Abrev.')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('nombre', models.CharField(max_length=20, null=True, verbose_name='Nombre')),
                ('region', models.CharField(blank=True, max_length=20, null=True, verbose_name='Región')),
                ('mensaje_perfil', models.CharField(blank=True, max_length=280, null=True, verbose_name='Mensaje de Perfil')),
                ('redes_facebook', models.CharField(blank=True, max_length=140, null=True, verbose_name='Perfil de Facebook')),
                ('redes_steam', models.CharField(blank=True, max_length=140, null=True, verbose_name='Usuario de Steam')),
                ('redes_twitch', models.CharField(blank=True, max_length=140, null=True, verbose_name='Canal de Twitch')),
                ('redes_youtube', models.CharField(blank=True, max_length=140, null=True, verbose_name='Canal de YouTube')),
                ('redes_instagram', models.CharField(blank=True, max_length=140, null=True, verbose_name='Usuario de Instagram')),
                ('redes_whatsapp', models.CharField(blank=True, max_length=140, null=True, verbose_name='Numero de WhatsApp')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RESERVA', 'Reserva'), ('LICENCIA', 'Licencia'), ('NO_MIEMBRO', 'No Miembro')], default=('ACTIVO', 'Activo'), max_length=20, verbose_name='Estado')),
                ('peloton', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pelotón')),
                ('escuadra', models.CharField(blank=True, max_length=20, null=True, verbose_name='Escuadra')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Imagen de Avatar')),
                ('clase1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clase1', to='stats.Clase', verbose_name='Clase 1')),
                ('clase2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clase2', to='stats.Clase', verbose_name='Clase 2')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombre de Misión')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Creación')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('fecha_finalizada', models.DateField(blank=True, null=True, verbose_name='Fecha Finalizada')),
                ('oficial', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Es Oficial?')),
                ('tipo', models.CharField(choices=[('CAMPANA', 'Campaña'), ('ENTRENAMIENTO', 'Entrenamiento'), ('IMPROVISADA', 'Improvisada'), ('GALA', 'Gala'), ('CURSO', 'Curso'), ('COOPERATIVA', 'Cooperativa'), ('OTRO', 'Otros')], default='OTRO', max_length=40, verbose_name='Tipo de misión')),
                ('estado', models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiende de aprobación'), ('EDITANDO', 'En edición'), ('PREPARADA', 'Preparada'), ('AGENDADA', 'Agendada'), ('FINALIZADA', 'Finalizada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=40, null=True, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (pública)')),
                ('notas_privadas', models.TextField(blank=True, null=True, verbose_name='Notas (Privadas)')),
                ('notas_editor', models.TextField(blank=True, null=True, verbose_name='Apuntes para los editores')),
                ('imagen', models.ImageField(blank=True, default='defaults/mision_default.png', null=True, upload_to='mision_logo/', verbose_name='Imagen')),
                ('briefing', models.FileField(blank=True, null=True, upload_to='briefings/', verbose_name='Briefing')),
                ('mapa', models.CharField(blank=True, choices=[('Altis', 'Altis'), ('Stratis', 'Stratis'), ('Malden', 'Malden'), ('VR', 'Realidad Virtual'), ('Bozcaada', 'Bozcaada'), ('Bootcamp_ACR', 'Bukovina'), ('Woodland_ACR', 'Bystrica'), ('chernarus', 'Chernarus'), ('chernarus_summer', 'Chernarus (Verano)'), ('Chernarus_Winter', 'Chernarus (Invierno)'), ('Desert_E', 'Desierto'), ('fallujah', 'Fallujah'), ('pja310', 'G.O.S. Al Rayak'), ('pj307', 'G.O.S. Dariyah'), ('MCN_HazarKot', 'Hazar-Kot (valle)'), ('Kidal', 'Kidal'), ('Kunduz', 'Kunduz, Afganistán'), ('porto ', 'Porto'), ('ProvingGrounds_PMC', 'Campo de pruebas'), ('intro ', 'Rahmadi'), ('sara ', 'Sahrani'), ('saralite', 'Sahrani del Sur'), ('sara_dbe1', 'Sahrani Unida'), ('Shapur_BAF', 'Shapur'), ('takistan', 'Takistán'), ('Mountains_ACR', 'Takistán (montañas)'), ('Tanoa', 'Tanoa'), ('utes', 'Utes'), ('zargabad', 'Zargabad'), ('prei_khmaoch_luong', 'Prei (Camboya)')], max_length=40, null=True, verbose_name='Mapa')),
                ('reporte', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Miembro', verbose_name='Autor')),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Campana', verbose_name='Campaña')),
                ('editores', models.ManyToManyField(blank=True, related_name='misiones_editadas', to='stats.Miembro', verbose_name='Editores')),
                ('responsables', models.ManyToManyField(blank=True, related_name='misiones_a_cargo', to='stats.Miembro', verbose_name='Responsables')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=40, verbose_name='Pais')),
                ('abreviatura', models.CharField(max_length=2, verbose_name='Abrev.')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=140, null=True, verbose_name='Mensaje')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=20, verbose_name='Rango')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='rango_img/', verbose_name='Imagen')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Unidad')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='unidad_img/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='wallpaper_img/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('miembro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Miembro', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='MisionGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(verbose_name='URL')),
                ('miembro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Miembro', verbose_name='Autor')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Mision', verbose_name='Mision')),
            ],
        ),
        migrations.AddField(
            model_name='miembro',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Nacionalidad', verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='rango',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Rango', verbose_name='Rango'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Rol', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Unidad', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('asistencia', models.CharField(choices=[('ASISTE', 'Asiste'), ('FALTA', 'Falta'), ('TARDE', 'Atraso'), ('JUSTIFICADA', 'Justificado'), ('RESERVA', 'Reserva'), ('LICENCIA', 'Licencia')], max_length=20, verbose_name='Asistencia')),
                ('tiempo_de_sesion', models.DurationField(default=0, verbose_name='Tiempo de Sesión')),
                ('requiere_atencion', models.BooleanField(default=False, verbose_name='Requiere Atención')),
                ('mensaje_notificacion', models.CharField(blank=True, max_length=140, null=True, verbose_name='Notificacion')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Miembro', verbose_name='Miembro')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Mision', verbose_name='Mision')),
            ],
            options={
                'ordering': ('-pk',),
                'unique_together': {('miembro', 'fecha')},
            },
        ),
    ]
