# Generated by Django 2.2.5 on 2019-09-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='oficial',
            field=models.BooleanField(default=True, verbose_name='Es Oficial?'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='tipo',
            field=models.CharField(choices=[('CAMPA', 'Campaña'), ('PRACT', 'Práctica'), ('IMPRO', 'Improvisada'), ('GALA', 'Gala'), ('INSTR', 'Instrucción'), ('COOP', 'Cooperativa'), ('OTRO', 'Otros')], default=('CAMPA', 'Campaña'), max_length=40, verbose_name='Tipo de misión'),
        ),
    ]
