# Generated by Django 2.2.5 on 2019-09-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_miembro_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='miembro',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='mision',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='rango',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='miembro',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Imagen de Avatar'),
        ),
    ]
