# Generated by Django 2.2.5 on 2019-09-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190919_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='campana_img/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='campana',
            name='notas_privadas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Privadas'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='asistencia',
            field=models.CharField(choices=[('ASISTE', 'Asiste'), ('FALTA', 'Falta'), ('TARDE', 'Atraso'), ('JUSTIFICADA', 'Justificado'), ('RESERVA', 'Reserva'), ('LICENCIA', 'Licencia')], max_length=20, verbose_name='Asistencia'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='tipo',
            field=models.CharField(choices=[('CAMP', 'Campaña Oficial'), ('CURSO', 'Curso'), ('OTRO', 'Otros')], default='CAMPANA', max_length=20, verbose_name='Tipo Campaña'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='estado',
            field=models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiende de aprobación'), ('EDITANDO', 'En edición'), ('PREPARADA', 'Preparada'), ('AGENDADA', 'Agendada'), ('FINALIZADA', 'Finalizada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=40, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='tipo',
            field=models.CharField(choices=[('CAMPANA', 'Campaña'), ('ENTRENAMIENTO', 'Entrenamiento'), ('IMPROVISADA', 'Improvisada'), ('GALA', 'Gala'), ('CURSO', 'Curso'), ('COOPERATIVA', 'Cooperativa'), ('OTRO', 'Otros')], default='OTRO', max_length=40, verbose_name='Tipo de misión'),
        ),
    ]
