# Generated by Django 2.2.5 on 2019-09-16 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20190915_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mision',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mision',
            name='notas',
        ),
        migrations.AddField(
            model_name='mision',
            name='autor',
            field=models.ManyToManyField(blank=True, null=True, related_name='misiones_creadas', to='stats.Miembro'),
        ),
        migrations.AddField(
            model_name='mision',
            name='briefing',
            field=models.FileField(blank=True, null=True, upload_to='briefings/', verbose_name='Briefing'),
        ),
        migrations.AddField(
            model_name='mision',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (pública)'),
        ),
        migrations.AddField(
            model_name='mision',
            name='estado',
            field=models.CharField(blank=True, choices=[('Borrador', 'Borrador'), ('Pendiende de aprobación', 'Pendiende de aprobación'), ('En edición', 'En edición'), ('Lista para jugar', 'Lista para jugar'), ('Rechazada', 'Rechazada'), ('Finalizada', 'Finalizada')], default=('Borrador', 'Borrador'), max_length=40, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='mision',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='mision',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Creación'),
        ),
        migrations.AddField(
            model_name='mision',
            name='fecha_finalizada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Finalizada'),
        ),
        migrations.AddField(
            model_name='mision',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Programada'),
        ),
        migrations.AddField(
            model_name='mision',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mision_logo/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='mision',
            name='mapa',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Mapa'),
        ),
        migrations.AddField(
            model_name='mision',
            name='notas_editor',
            field=models.TextField(blank=True, null=True, verbose_name='Notas al Editor'),
        ),
        migrations.AddField(
            model_name='mision',
            name='notas_privadas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Privadas'),
        ),
        migrations.AddField(
            model_name='mision',
            name='responsables',
            field=models.ManyToManyField(blank=True, null=True, related_name='misiones_a_cargo', to='stats.Miembro'),
        ),
        migrations.RemoveField(
            model_name='mision',
            name='editores',
        ),
        migrations.AddField(
            model_name='mision',
            name='editores',
            field=models.ManyToManyField(blank=True, null=True, related_name='misiones_editadas', to='stats.Miembro'),
        ),
    ]
