# Generated by Django 2.2.5 on 2019-09-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20190915_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='reporte',
            field=models.FileField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
