# Generated by Django 2.2.5 on 2019-09-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20190922_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='nombre',
            field=models.CharField(max_length=140, verbose_name='Nombre Campaña'),
        ),
    ]
