# Generated by Django 2.2.5 on 2019-09-17 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20190916_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mision',
            name='autor',
        ),
        migrations.AddField(
            model_name='mision',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Miembro', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='editores',
            field=models.ManyToManyField(blank=True, null=True, related_name='misiones_editadas', to='stats.Miembro', verbose_name='Editores'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='responsables',
            field=models.ManyToManyField(blank=True, null=True, related_name='misiones_a_cargo', to='stats.Miembro', verbose_name='Responsables'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='tipo',
            field=models.CharField(choices=[('Misión Oficial', 'Misión Oficial'), ('Entrenamiento', 'Entrenamiento'), ('Improvisada', 'Improvisada'), ('Gala', 'Gala'), ('Instrucción', 'Instrucción'), ('Otros', 'Otros')], default=('Misión Oficial', 'Misión Oficial'), max_length=40, verbose_name='Tipo de misión'),
        ),
    ]
