# Generated by Django 2.2.5 on 2019-11-18 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20190922_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='mensaje_notificacion',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Notificacion'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('RESERVA', 'Reserva'), ('LICENCIA', 'Licencia'), ('NO_MIEMBRO', 'No Miembro')], default=('ACTIVO', 'Activo'), max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='mapa',
            field=models.CharField(blank=True, choices=[('Altis', 'Altis'), ('Stratis', 'Stratis'), ('Malden', 'Malden'), ('VR', 'Realidad Virtual'), ('Bozcaada', 'Bozcaada'), ('Bootcamp_ACR', 'Bukovina'), ('Woodland_ACR', 'Bystrica'), ('chernarus', 'Chernarus'), ('chernarus_summer', 'Chernarus (Verano)'), ('Chernarus_Winter', 'Chernarus (Invierno)'), ('Desert_E', 'Desierto'), ('fallujah', 'Fallujah'), ('pja310', 'G.O.S. Al Rayak'), ('pj307', 'G.O.S. Dariyah'), ('MCN_HazarKot', 'Hazar-Kot (valle)'), ('Kidal', 'Kidal'), ('Kunduz', 'Kunduz, Afganistán'), ('porto ', 'Porto'), ('ProvingGrounds_PMC', 'Campo de pruebas'), ('intro ', 'Rahmadi'), ('sara ', 'Sahrani'), ('saralite', 'Sahrani del Sur'), ('sara_dbe1', 'Sahrani Unida'), ('Shapur_BAF', 'Shapur'), ('takistan', 'Takistán'), ('Mountains_ACR', 'Takistán (montañas)'), ('Tanoa', 'Tanoa'), ('utes', 'Utes'), ('zargabad', 'Zargabad'), ('prei_khmaoch_luong', 'Prei (Camboya)')], max_length=40, null=True, verbose_name='Mapa'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='notas_editor',
            field=models.TextField(blank=True, null=True, verbose_name='Apuntes para los editores'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='notas_privadas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas (Privadas)'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='oficial',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Es Oficial?'),
        ),
    ]
