# Generated by Django 2.2.5 on 2019-11-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_miembro_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='mensaje_perfil',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Mensaje de Perfil'),
        ),
    ]
