# Generated by Django 2.2.5 on 2019-11-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_miembro_mensaje_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='redes_facebook',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Perfil de Facebook'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='redes_instagram',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Usuario de Instagram'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='redes_steam',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Usuario de Steam'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='redes_twitch',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Canal de Twitch'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='redes_whatsapp',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Numero de WhatsApp'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='redes_youtube',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Canal de YouTube'),
        ),
    ]
