# Generated by Django 2.1.2 on 2019-12-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20191118_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='rango',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rango_img/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='unidad_img/', verbose_name='Imagen'),
        ),
    ]
