# Generated by Django 2.1.2 on 2019-12-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20191217_1240'),
        ('stats', '0012_auto_20191217_1056'),
    ]

    operations = [
    ]
