# Generated by Django 2.1.2 on 2020-01-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_misiongaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='wallpaper_img/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('miembro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Miembro', verbose_name='Autor')),
            ],
        ),
        migrations.AddField(
            model_name='misiongaleria',
            name='miembro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Miembro', verbose_name='Autor'),
        ),
    ]
