# Generated by Django 2.2.9 on 2020-02-02 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_auto_20200109_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=140, null=True, verbose_name='Mensaje')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
        ),
    ]
