# Generated by Django 2.1.7 on 2019-09-11 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('asistencia', models.CharField(choices=[('Asiste', 'Asiste'), ('Falta', 'Falta'), ('Atraso', 'Atraso'), ('Justificado', 'Justificado'), ('Reserva', 'Reserva'), ('Licencia', 'Licencia')], max_length=20, verbose_name='Asistencia')),
                ('tiempo_de_sesion', models.DurationField(default=0, verbose_name='Tiempo de Sesión')),
                ('requiere_atencion', models.BooleanField(default=False, verbose_name='Requiere Atención')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=20, verbose_name='Clase')),
                ('abreviatura', models.CharField(default='-', max_length=10, verbose_name='Abrev.')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Reserva', 'Reserva'), ('Licencia', 'Licencia'), ('No Miembro', 'No Miembro')], default=('Activo', 'Activo'), max_length=20, verbose_name='Estado')),
                ('peloton', models.CharField(default='1', max_length=20, verbose_name='Pelotón')),
                ('escuadra', models.CharField(default='-', max_length=20, verbose_name='Escuadra')),
                ('clase1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clase1', to='asistencia.Clase', verbose_name='Clase 1')),
                ('clase2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clase2', to='asistencia.Clase', verbose_name='Clase 2')),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de Misión')),
                ('reporte', models.FileField(upload_to='reportes/')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('Misión Oficial', 'Misión Oficial'), ('Entrenamiento', 'Entrenamiento'), ('Improvisada', 'Improvisada'), ('Gala', 'Gala'), ('Instrucción', 'Instrucción'), ('Otros', 'Otros')], default=('Misión Oficial', 'Misión Oficial'), max_length=20, verbose_name='Tipo de misión')),
                ('nombre_campa', models.CharField(max_length=40, verbose_name='Nombre de Campaña')),
                ('editores', models.CharField(max_length=128, verbose_name='Editores')),
                ('notas', models.CharField(max_length=255, verbose_name='Notas')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=20, verbose_name='Rango')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Unidad')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
        ),
        migrations.AddField(
            model_name='miembro',
            name='nacionalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Nacionalidad', verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='rango',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Rango', verbose_name='Rango'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Rol', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Unidad', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Miembro', verbose_name='Miembro'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='mision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.Mision', verbose_name='Mision'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('miembro', 'fecha')},
        ),
    ]
