# Generated by Django 2.1.7 on 2019-09-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='editores',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Editores'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='notas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas'),
        ),
    ]
