# Generated by Django 2.1.7 on 2019-04-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('asistencia', models.CharField(choices=[('Asiste', 'Asiste'), ('Falta', 'Falta'), ('Atraso', 'Atraso'), ('Justificado', 'Justificado'), ('Reserva', 'Reserva'), ('Licencia', 'Licencia')], max_length=20, verbose_name='Asistencia')),
                ('tiempo_de_sesion', models.DurationField(default=0, verbose_name='Tiempo de Sesión')),
                ('requiere_atencion', models.BooleanField(default=False, verbose_name='Requiere Atención')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=20, verbose_name='Clase')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=20, verbose_name='Rango')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Unidad')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abrev.')),
            ],
        ),
        migrations.AlterField(
            model_name='miembro',
            name='clase1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clase1', to='asistencia.Clase', verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='clase2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clase2', to='asistencia.Clase', verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Nacionalidad', verbose_name='Rango'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='rango',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Rango', verbose_name='Rango'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Rol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Unidad', verbose_name='Rango'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Miembro', verbose_name='Miembro'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('miembro', 'date')},
        ),
    ]
