# Generated by Django 2.1.7 on 2019-04-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20190406_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='abreviatura',
            field=models.CharField(default='-', max_length=10, verbose_name='Abrev.'),
        ),
    ]
