# Generated by Django 2.1.7 on 2019-04-06 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_clase_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='rango',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='escuadra',
            field=models.CharField(default='-', max_length=20, verbose_name='Escuadra'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Reserva', 'Reserva'), ('Licencia', 'Licencia'), ('No Miembro', 'No Miembro')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Nacionalidad', verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='peloton',
            field=models.CharField(default='-', max_length=20, verbose_name='Pelotón'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.Unidad', verbose_name='Unidad'),
        ),
    ]
